### ISSUE TITLE
Uncaught TypeError: createEngine is not a function

### ISSUE THREAD

**Issue by TrySpace** [michaelcontento/redux-storage-engine-localstorage#25]
When I try your example I get the error: `createEngine is not a function`, which is true when I look at the source, it is not defined anywhere..

**Comment by michaelcontento** [comment]
`createEngine` is the name where the import of 

```js
import createEngine from 'redux-storage-engine-localstorage';
``` 

will land. Which, btw, is only ES6 syntax for 

```js
var createEngine = require('redux-storage-engine-localstorage').default;
```
